[config]
schemaVersion = "0.0.1"

[package]
namespace = "helskog"
name = "Crossveil"
versionNumber = "1.0.0"
description = "Fully replace the standard Cursors/Crosshairs with your own!"
websiteUrl = "https://github.com/helskog/Crossveil"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_V_Rising = "1.691.3"

[build]
icon = "./logo_256.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./bin/Release/net6.0/Crossveil.dll"
target = "./Crossveil.dll"

[[build.copy]]
source = "../CHANGELOG.md"
target = "./CHANGELOG.md"

[publish]
communities = ["v-rising"]
repository = "https://thunderstore.io"
[publish.categories]
v-rising = ["Client", "Mods", "Oakveil Update"]